#!/usr/bin/env python3
"""Regenerate docs/api.md from the running app's routes and their declared permissions."""
import inspect
import os
import re
import sys
from pathlib import Path

os.environ.setdefault("MUNSHI_NO_AUTOAPP", "1"); os.environ.setdefault("MLFLOW_DISABLE_AGENT_HINT", "1"); os.environ.setdefault("LOG_LEVEL", "WARNING")
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from fastapi.routing import APIRoute  # noqa: E402

from munshi.web.app import build_app  # noqa: E402


def walk(routes):
    for r in routes:
        if isinstance(r, APIRoute):
            yield r
        elif hasattr(r, "routes"):
            yield from walk(r.routes)
        elif hasattr(r, "original_router"):          # FastAPI ≥0.140 keeps included routers as a node
            yield from walk(r.original_router.routes)


app = build_app(in_memory=True, demo=False, scheduler=False)
rows = []
for r in walk(app.routes):
    if not r.path.startswith(("/api", "/i/", "/s/", "/healthz")) or r.path in ("/api/docs", "/api/openapi.json"):
        continue
    src = inspect.getsource(r.endpoint)
    m = re.search(r'context\("([^"]+)"\)|require\("([^"]+)"\)', src)
    perm = (m.group(1) or m.group(2)) if m else ("session" if "Depends(current)" in src else "public")
    doc = (r.endpoint.__doc__ or "").strip().split("\n")[0]
    for meth in sorted(r.methods - {"HEAD", "OPTIONS"}):
        rows.append((r.path, meth, perm, doc))
rows.sort()
out = ["# API reference", "",
       "Every route, its method and the permission it requires. Permissions map to roles in",
       "`src/munshi/auth/principal.py`; `session` means any signed-in user; `public` needs no token.",
       "In development the interactive explorer is at `/api/docs`.", "",
       "Authentication: `POST /api/session` returns a token; send it as `X-Session: <token>` (or",
       "`Authorization: Bearer <token>`). Errors are `{\"detail\": \"...\"}` with a 4xx status; validation",
       "errors are 422 with Pydantic's field list. Sign-in and sign-up are rate-limited per address.", "",
       "| Route | Method | Permission | Notes |", "|---|---|---|---|"]
for p, m, perm, doc in rows:
    out.append(f"| `{p}` | {m} | `{perm}` | {doc} |")
out += ["", f"{len(rows)} routes. Generated by `scripts/api_doc.py`."]
Path("docs/api.md").write_text("\n".join(out) + "\n")
print(len(rows), "routes")
