"""The payslip an employee actually gets: printable HTML and a PDF (reportlab), in the invoice.py style.

Layout follows the Punjab Labour Code 2026 s.165(15) prescribed content (accounts.PAYSLIP_SECTIONS): basic,
allowances, gross, itemised deductions, total deductions, net, other payments (overtime, commission, bonus), total
payment, and leave balances -- plus year-to-date tax, the employer's EOBI as a memo, payment status, the owner's cash
exemption when a payment relied on it, and the "not tax advice" boundary text. The input is repo.payslip(...)'s dict.
Salary slips are never public links: the routes serve them to the owner, or to the employee whose slip it is."""
from __future__ import annotations

import html
import io


def _money(v) -> str:
    return "" if v is None else f"{v:,.2f}"


def _leave(d: dict) -> str:
    return ", ".join(f"{k} {v:g}" for k, v in (d or {}).items())


def render_html(d: dict) -> str:
    m, esc = d["meta"], html.escape
    rows = "".join(
        f"<tr{' class=em' if r.get('_em') else ''}><td>{esc(str(r['item']))}</td><td class=n>{_money(r['earnings'])}</td>"
        f"<td class=n>{_money(r['deductions'])}</td></tr>" for r in d["table"]["rows"])
    pays = "".join(f"<li>{esc(p['paid_on'])} · Rs {p['amount']:,.2f} · {esc(p['method'])}{' (owner exemption)' if p['cash_exemption'] else ''}"
                   f"{' · reversal of ' + esc(p['reversal_of']) if p['reversal_of'] else ''}</li>" for p in d["payments"])
    exempt = f"<p class=warn>{esc(m['cash_exemption_note'])}: {esc(m['cash_exemption_reason'] or '')}</p>" if m.get("cash_exemption") else ""
    reversed_ = "<p class=warn>This payroll run was reversed; this slip is void.</p>" if d.get("status") == "reversed" else ""
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Payslip {esc(m['slip_no'])} · {esc(m['name'])}</title>
<style>
body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#f4f2ec;color:#1b1b1b}}
.sheet{{max-width:680px;margin:0 auto;background:#fff;padding:28px 26px 34px}}
h1{{font-size:22px;margin:0}} h2{{font-size:15px;margin:22px 0 6px;color:#555;text-transform:uppercase;letter-spacing:.06em}}
.head{{display:flex;justify-content:space-between;gap:16px;border-bottom:3px solid #1b1b1b;padding-bottom:12px}}
.muted{{color:#666;font-size:13px}} table{{width:100%;border-collapse:collapse;margin-top:8px;font-size:14px}}
th,td{{padding:7px 6px;border-bottom:1px solid #e5e5e5;text-align:left;vertical-align:top}} th{{font-size:12px;color:#666;text-transform:uppercase}}
.n{{text-align:right;font-variant-numeric:tabular-nums}} tr.em td{{font-weight:700;border-top:1px solid #1b1b1b}}
.badge{{display:inline-block;background:#1b1b1b;color:#fff;font-size:12px;padding:3px 8px;border-radius:4px;letter-spacing:.06em}}
.grid{{display:grid;grid-template-columns:1fr 1fr;gap:4px 18px;font-size:13px}} .warn{{background:#fff4d6;padding:8px;border-radius:4px;font-size:13px}}
.foot{{margin-top:26px;font-size:12px;color:#666;border-top:1px solid #e5e5e5;padding-top:10px}}
@media print{{body{{background:#fff}}.sheet{{padding:0}}}}
</style></head><body><div class="sheet">
<div class="head"><div><h1>{esc(m['business_name'])}</h1><div class="muted">Salary slip · {esc(m['month'])}</div></div>
<div style="text-align:right"><span class="badge">PAYSLIP</span><div style="font-weight:700;margin-top:6px">{esc(m['slip_no'])}</div>
<div class="muted">{esc(m['paid_status'])}</div></div></div>
<h2>Employee</h2><div class="grid">
<div><b>{esc(m['name'])}</b> · {esc(m['emp_no'])}</div><div>{esc(m['designation'])}</div>
<div>CNIC: {('xxxxx-xxxxxxx-' + esc(m['cnic_last4'])) if m['cnic_last4'] else '-'}</div><div>Joined: {esc(m['joined_on'])}</div>
<div>Pay basis: {esc(m['pay_basis'])}</div><div>Days worked: {m['days_worked']:g} · unpaid absence: {m['unpaid_absent']:g}</div>
<div>Paid leave this month: {esc(_leave(m['paid_leave']))}</div><div>Paid by: {esc(m['pay_method'])}</div></div>
<table><thead><tr><th>Item</th><th class=n>Earnings</th><th class=n>Deductions</th></tr></thead><tbody>{rows}</tbody></table>
{exempt}{reversed_}
<h2>Leave balances (days)</h2><div>{esc(_leave(m['leave_balances']))}</div>
<h2>Tax year {m['tax_year']} to date</h2><div class="grid"><div>Taxable pay: Rs {m['ytd_taxable']:,.2f}</div><div>Tax withheld: Rs {m['ytd_tax']:,.2f}</div>
<div>Employer EOBI (memo): Rs {m['employer_eobi']:,.2f}</div><div>Employer social security (memo): Rs {m['employer_social_security']:,.2f}</div></div>
<h2>Payments</h2>{'<ul>' + pays + '</ul>' if pays else '<p class=muted>Not paid yet.</p>'}
<p><b>Paid Rs {m['paid']:,.2f} · balance due Rs {m['balance_due']:,.2f}</b></p>
<div class="foot">{esc(m['boundary'])}<br>Generated by Munshi for {esc(m['business_name'])}. Run {esc(m['run_id'])}.</div>
</div></body></html>"""


def render_pdf(d: dict) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    m, esc = d["meta"], html.escape
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
                            title=f"Payslip {m['slip_no']}")
    ss = getSampleStyleSheet()
    h = ParagraphStyle("h", parent=ss["Title"], fontSize=18, alignment=0, spaceAfter=2)
    muted = ParagraphStyle("m", parent=ss["Normal"], textColor=colors.HexColor("#666666"), fontSize=9)
    body = ss["Normal"]
    story = [Paragraph(esc(m["business_name"]), h), Paragraph(f"Salary slip · {esc(m['month'])}", muted), Spacer(1, 6),
             Paragraph(f"<b>PAYSLIP {esc(m['slip_no'])}</b> · {esc(m['paid_status'])}", body), Spacer(1, 8),
             Paragraph(f"<b>{esc(m['name'])}</b> ({esc(m['emp_no'])}) · {esc(m['designation'])} · joined {esc(m['joined_on'])}", body),
             Paragraph(esc(f"CNIC ending {m['cnic_last4'] or '-'} · {m['pay_basis']} · days worked {m['days_worked']:g} · unpaid absence "
                           f"{m['unpaid_absent']:g} · paid leave {_leave(m['paid_leave'])} · paid by {m['pay_method']}"), muted), Spacer(1, 8)]
    data = [["Item", "Earnings", "Deductions"]] + [[r["item"], _money(r["earnings"]), _money(r["deductions"])] for r in d["table"]["rows"]]
    t = Table(data, colWidths=[100 * mm, 36 * mm, 36 * mm])
    style = [("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("ALIGN", (1, 0), (-1, -1), "RIGHT"), ("LINEBELOW", (0, 0), (-1, 0), 1, colors.black),
             ("LINEBELOW", (0, 1), (-1, -1), 0.3, colors.HexColor("#dddddd")), ("FONTSIZE", (0, 0), (-1, -1), 9.5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5)]
    for i, r in enumerate(d["table"]["rows"], start=1):
        if r.get("_em"):
            style.append(("FONTNAME", (0, i), (-1, i), "Helvetica-Bold"))
    t.setStyle(TableStyle(style))
    story += [t, Spacer(1, 8)]
    if m.get("cash_exemption"):
        story.append(Paragraph(esc(f"{m['cash_exemption_note']}: {m['cash_exemption_reason'] or ''}"), body))
    if d.get("status") == "reversed":
        story.append(Paragraph("This payroll run was reversed; this slip is void.", body))
    story += [Paragraph(f"Leave balances (days): {esc(_leave(m['leave_balances']))}", body),
              Paragraph(f"Tax year {m['tax_year']} to date: taxable Rs {m['ytd_taxable']:,.2f}, tax withheld Rs {m['ytd_tax']:,.2f}. "
                        f"Employer EOBI (memo) Rs {m['employer_eobi']:,.2f}.", body),
              Paragraph(f"<b>Paid Rs {m['paid']:,.2f} · balance due Rs {m['balance_due']:,.2f}</b>", body), Spacer(1, 12),
              Paragraph(esc(m["boundary"]), muted), Paragraph(f"Generated by Munshi. Run {esc(m['run_id'])}.", muted)]
    doc.build(story)
    return buf.getvalue()


def whatsapp_text(d: dict) -> str:
    """For the owner to forward (a client-side wa.me link; nothing is queued in the outbox)."""
    m = d["meta"]
    txt = (f"{m['business_name']}: salary slip {m['slip_no']} for {m['name']}, {m['month']}. Net pay Rs {d['net']:,.2f}"
           f" (gross Rs {d['gross']:,.2f}, deductions Rs {d['deductions']:,.2f}). Paid Rs {m['paid']:,.2f}.")
    if m.get("cash_exemption"):
        txt += f" {m['cash_exemption_note']}."
    return txt
